# Site settings
title: Parker's Portfolio
email: parker.e.hix@gmail.com
description: > # keep this and put description below
  Bookmark this to keep an eye on my project updates!
url: "https://phix-portfolio.github.io" # the base hostname & protocol for your site
linkedin_url: "www.linkedin.com/in/phix03"
github_username: emanuelhix
twitter_username: psudar_
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
